# Generated by Django 5.1.7 on 2025-03-26 14:42

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_main_grade_options_remove_main_grade_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название оценки/рейтинга', max_length=100, verbose_name='Название оценки')),
                ('value', models.DecimalField(decimal_places=2, help_text='Оценка от 0 до 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Значение оценки')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание оценки', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Основная оценка',
                'verbose_name_plural': 'Основные оценки',
                'ordering': ['-value'],
            },
        ),
        migrations.AlterModelOptions(
            name='main_grade',
            options={},
        ),
        migrations.RemoveField(
            model_name='main_grade',
            name='description',
        ),
        migrations.RemoveField(
            model_name='main_grade',
            name='name',
        ),
        migrations.RemoveField(
            model_name='main_grade',
            name='value',
        ),
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_grade',
            name='grade',
            field=models.CharField(choices=[('A', 'Отлично (90-100)'), ('B', 'Хорошо (80-89)'), ('C', 'Удовлетворительно (70-79)'), ('D', 'Неудовлетворительно (60-69)'), ('F', 'Не сдано (0-59)')], default=django.utils.timezone.now, max_length=1, verbose_name='Оценка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
